from datetime import datetime
from typing import Protocol

from .types import Profile, SessionContext, StoredSession


class AuthBackend(Protocol):
    def create_auth_user(self, email: str, password: str) -> str: ...
    def delete_auth_user(self, user_id: str) -> None: ...
    def verify_password(self, email: str, password: str) -> str | None: ...
    def send_password_reset(self, email: str, redirect_url: str) -> None: ...
    def update_password(self, recovery_access_token: str, password: str) -> str: ...
    def create_profile(self, profile: Profile) -> Profile: ...
    def get_profile_by_id(self, user_id: str) -> Profile | None: ...
    def get_profile_by_username(self, normalized: str) -> Profile | None: ...
    def get_profile_by_email(self, normalized: str) -> Profile | None: ...
    def create_session(self, session: StoredSession) -> None: ...
    def get_session(self, token_hash: str, now: datetime) -> SessionContext | None: ...
    def revoke_session(self, token_hash: str, now: datetime) -> None: ...
    def revoke_user_sessions(self, user_id: str, now: datetime) -> int: ...
    def resubmit_profile(self, user_id: str, now: datetime) -> Profile: ...
    def list_users(self, status: str | None) -> list[Profile]: ...
    def transition_user(
        self,
        actor_id: str,
        target_id: str,
        action: str,
        expected_status: str,
        reason: str,
        ip_hash: str,
        now: datetime,
    ) -> Profile: ...
    def change_role(
        self,
        actor_id: str,
        target_id: str,
        role: str,
        reason: str,
        ip_hash: str,
        now: datetime,
    ) -> Profile: ...
    def bootstrap_super_admin(
        self,
        target_id: str,
        reason: str,
        now: datetime,
    ) -> Profile: ...
    def force_revoke_sessions(
        self,
        actor_id: str,
        target_id: str,
        reason: str,
        ip_hash: str,
        now: datetime,
    ) -> int: ...
    def delete_user(
        self,
        actor_id: str,
        target_id: str,
        reason: str,
        ip_hash: str,
        now: datetime,
    ) -> dict: ...
    def list_audit_logs(self, limit: int) -> list[dict]: ...
